drop table IF EXISTS COMEANDEAT.FoodProvider;
drop table IF EXISTS COMEANDEAT.Reviews;
drop table IF EXISTS COMEANDEAT.MenuItem;
drop table IF EXISTS COMEANDEAT.Addition;
drop table IF EXISTS COMEANDEAT.Order;
drop table IF EXISTS COMEANDEAT.OrderMenuItem;

CREATE TABLE IF NOT EXISTS COMEANDEAT.FoodProvider (
	ID 				CHAR(36) NOT NULL,
	Name			VARCHAR(255) NOT NULL,
	Address 		VARCHAR(255) NOT NULL,
	ContactName		VARCHAR(255) NOT NULL,
	ContactNumber 	VARCHAR(255) NOT NULL,
	WorkingHours	VARCHAR(255) NOT NULL,
	DeliveryPrice	VARCHAR(255) NOT NULL,
	UNIQUE KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMEANDEAT.Reviews (
	ID 				CHAR(36) NOT NULL,
	FoodProviderID	CHAR(36) NOT NULL,
	Rating			VARCHAR(255) NOT NULL,
	Text			VARCHAR(255) NOT NULL,
	UNIQUE KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMEANDEAT.MenuItem (
	ID 				CHAR(36) NOT NULL,
	FoodProviderID	CHAR(36) NOT NULL,
	Description 	VARCHAR(255) NOT NULL,
	Price 			VARCHAR(255) NOT NULL,
	UNIQUE KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMEANDEAT.Addition (
	ID 				CHAR(36) NOT NULL,
	MenuID			CHAR(36) NOT NULL,
	Name			VARCHAR(255) NOT NULL,
	Price 			VARCHAR(255) NOT NULL,
	UNIQUE KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMEANDEAT.Order (
	ID 				CHAR(36) NOT NULL,
	CustomerName	VARCHAR(255) NOT NULL,
	Date			VARCHAR(255) NOT NULL,
	FoodProviderID	CHAR(36) NOT NULL,
	UNIQUE KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMEANDEAT.OrderMenuItem (
	ID 				CHAR(36) NOT NULL,
	OrderID			CHAR(36) NOT NULL,
	FoodProviderID	CHAR(36) NOT NULL,
	MenuID			CHAR(36) NOT NULL,
	AdditionID		CHAR(36) NOT NULL,
	UNIQUE KEY (ID)
);
