package com.comeandeat;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.comeandeat.entity.FoodOrder;
import com.comeandeat.repository.FoodOrderRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class ApplicationController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private FoodOrderRepository orderRepository;

	@GetMapping(path = "/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		FoodOrder order = new FoodOrder();
		order.setCustomerName(name);
		Date date = new Date();
		order.setOrderDate(date);
		orderRepository.save(order);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<FoodOrder> getAllUsers() {
		// This returns a JSON or XML with the users
		return orderRepository.findAll();
	}

}
